# Generated by Django 4.2.7 on 2023-12-01 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0002_categoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
